version: '3.9'

services:

  nas-manager:
    image: nas-manager:0.0.1
    ports:
      - 6000:6000
    restart: on-failure

  envoyproxy:
    image: envoyproxy
    build:
      context: ./envoy/.
      dockerfile: dockerfile
    ports:
      - 6060:6060
      - 9901:9901